### ISSUE TITLE
Show posts from #polish tag only.

### ISSUE THREAD

**Issue by mariuszkarowski** [mariuszkarowski/busy#1]
#### Expected behavior

I want to show posts from #polish tag on homepage. (for non logged in users)

**Comment by fervi** [comment]
Jutro sprawdzę, coś mi się udało - ale razem jesteśmy amatorami w tym :)
Edit: Działa, ale rozwiązanie jest mało eleganckie - będę szukał optymalizacji

**Comment by fervi** [comment]
Kod został dodany, proszę o sprawdzenie i dodanie

**Comment by mariuszkarowski** [comment]
Działa. Dziękuję.
