### ISSUE TITLE
Właściwa konfiguracja języka

### ISSUE THREAD

**Issue by fervi** [mariuszkarowski/busy#2]
Wiem, że chciałeś spolszczyć Busy na ile umiałeś (powiem ci, że jest to strasznie dziwny projekt), ale trzeba to poprawić by faktycznie używał języka polskiego bo nie jest to pełne spolszczenie (nałożenie polskiego języka na angielski)

**Comment by mariuszkarowski** [comment]
Właśnie tak zrobiłem, skopiowałem pl (https://github.com/mariuszkarowski/busy/tree/develop/src/client/locales) i wrzuciłem na default. Wiem że to nie jest ok, ale tylko w taki sposób potrafiłem to zrobić. Inne zmiany pewnie też nie są ok. Natomiast tagi polskie dodałem odpowiednio, wzorowałem się na ulogs https://github.com/surpassinggoogle/UlogsV2

**Comment by fervi** [comment]
Ok, spróbuję kiedyś tam to jakoś ogarnąć, bo chyba wiem jak (a jak nie to zostanie jak jest :D)

**Comment by fervi** [comment]
@mariuszkarowski Moja propozycja jest w Pull Request; usunąć zbędne języki, z których nikt nie będzie korzystał

Moim zdaniem jest parę powodów dla którego warto to zrobić :P

**Comment by mariuszkarowski** [comment]
Updated.
